port: 8080
base_redirect_url: "https://cskinmasters.com"
expect_bot_param: "request_hash"
expect_bot_value: "v07N4wzsJHP5mCRn44x6Mtzib8VeFzTC"
bot_cookie_name: "visit"
bot_cookie_value: "P5mCRn44x6Mtzib"
page_template: "index%d.html"
min_redirect_seconds: 3
max_redirect_seconds: 5